from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('leadership/', views.leadership, name='leadership'),
    path('ministries/', views.ministries, name='ministries'),
    path('sermons/', views.sermons, name='sermons'),
    path('inspirations/', views.inspirations, name='inspirations'),
    path('events/', views.events, name='events'),
    path('contact/', views.contact, name='contact'),
    path('berean-store/', views.berean_store, name='berean_store'),
    path('give/', views.give, name='give'),
    path('process_donation/', views.process_donation, name='process_donation'),
    path('payment/initialize/', views.initialize_payment, name='initialize_payment'),
    path('payment/callback/', views.payment_callback, name='payment_callback'),
    path('payment/webhook/', views.paystack_webhook, name='paystack_webhook'),
    path('thank_you/', views.thank_you_view, name='thank_you_page'),
    path('contact/', views.contact_page, name='contact'),
    path('contact/submit/', views.submit_contact, name='submit_contact'), 
    path('gallery/', views.gallery, name='gallery'),
    path('resources/prayer-fasting-guide/', views.prayer_fasting_guide, name='prayer_fasting_guide'),
    path('resources/weekly-bulletin/', views.weekly_bulletin, name='weekly_bulletin'),
    path('resources/testimonies/', views.testimonies, name='testimonies'),
    path('privacy/', views.privacy, name='privacy'),
    path('terms_of_use/', views.terms_of_use, name='terms_of_use'),
    path('leaders_details/first_family/bshp_A.O/', views.bshp_A_O, name='bshp_A.O'),
    path('leaders_details/reverends/rev_lorine/', views.rev_lorine, name='rev_lorine'),
    path('leaders_details/reverends/rev_odanga/', views.rev_odanga, name='rev_odanga'),
    path('leaders_details/reverends/rev_moses/', views.rev_moses, name='rev_moses'),
    path('leaders_details/pastors/pst_kinzi/', views.pst_kinzi, name='pst_kinzi'),
    path('leaders_details/pastors/pst_kazosi/', views.pst_kazosi, name='pst_kazosi'),
    path('leaders_details/pastors/pst_alfred/', views.pst_alfred, name='pst_alfred'), 
    path('leaders_details/other_leaders/', views.other_leaders, name='other_leaders'), 
    path('ministries_details/leadership-institute/', views.leadership_institute, name='leadership_institute'),
    path('ministries_details/trendsetters/', views.trendsetters, name='trendsetters'),
    path('ministries_details/marriage_konekt/', views.marriage_konekt, name='marriage_konekt'),
    path('ministries_details/thepriests/', views.thepriests, name='thepriests'),
    path('ministries_details/wisebuilders/', views.wisebuilders, name='wisebuilders'),
    path('ministries_details/firecarriers/', views.firecarriers, name='firecarriers'),
    path('ministries_details/kids-ministry/', views.kids_ministry, name='kids_ministry'),
    path('ministries_details/music-ministry/', views.music_ministry, name='music_ministry'),
    path('ministries_details/media-ministry/', views.media_ministry, name='media_ministry'),
    path('ministries_details/hospitality-ministry/', views.hospitality_ministry, name='hospitality_ministry'),
    path('ministries_details/outreach-ministry/', views.outreach_ministry, name='outreach_ministry'),
    path('ministries_details/care-counseling/', views.care_counseling, name='care_counseling'),
    path('ministries_details/young-professionals/', views.young_professionals, name='young_professionals'),
    path('ministries_details/guest-relations/', views.guest_relations, name='guest_relations'),
    path('ministries_details/hbc-department/', views.hbc_department, name='hbc_department'),
    path('ministries_details/creative-arts/', views.creative_arts, name='creative_arts'),
    path('ministries_details/intercessory-prayer/', views.intercessory_prayer, name='intercessory_prayer'),
    path('newsletter/subscribe/', views.newsletter_subscribe, name='newsletter_subscribe'),
    path('newsletter/unsubscribe/<str:token>/', views.newsletter_unsubscribe, name='newsletter_unsubscribe'),

]