# Generated by Django 5.2.2 on 2025-10-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_offering_giving_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='giving_type',
            field=models.CharField(choices=[('tithe', 'Tithe & Offerings'), ('missions', 'Missions & Outreach'), ('building', 'Building Fund'), ('men', 'Men Ministry'), ('women', 'Women Ministry'), ('youth', 'Youth Ministry'), ('kids', 'Kids Ministry'), ('ministries', 'Other Ministries'), ('department', 'Departmental Fund'), ('general', 'General Fund')], max_length=50),
        ),
    ]
